export const dataForSubtitlesMenu = [
  { value: 'Lingue Audio', title: true, id:1},
  { value: 'ita', id: 2},
  { value: 'eng', id: 3},
  { value: 'fra', id: 4},
  { value: 'ben', id: 5},
  { value: 'gla', id: 6},
  { value: 'ind', id: 8},
  { value: 'nor', id: 9},
  { value: 'rus', id: 10},
  { value: 'slv', id: 11},
  { value: 'Sottotitoli', title: true, id: 12},
  { value: 'Disattiva sottotitoli', disableSubTitle: true, id: 13},
  { value: 'ita', id: 14},
  { value: 'eng', id: 15},
  { value: 'fra', id: 16},
  { value: 'ben', id: 17},
  { value: 'gla', id: 18},
  { value: 'ind', id: 19},
  { value: 'nor', id: 20},
  { value: 'rus', id: 21},
  { value: 'slv', id: 22},
]
