export const dataForSubtitlesMenu = [
  { value: 'Lingue Audio', title: true, id:1},
  { value: 'Italiano', id: 2},
  { value: 'English', id: 3},
  { value: 'Français', id: 4},
  { value: 'বাংলা', id: 5},
  { value: 'Gàidhlig', id: 6},
  { value: 'Bahasa Indonesia', id: 8},
  { value: 'Norsk', id: 9},
  { value: 'русский', id: 10},
  { value: 'Slovenščina', id: 11},
  { value: 'Sottotitoli', title: true, id: 12},
  { value: 'Disattiva sottotitoli', disableSubTitle: true, id: 13},
  { value: 'Italiano', id: 14},
  { value: 'English', id: 15},
  { value: 'Français', id: 16},
  { value: 'বাংলা', id: 17},
  { value: 'Gàidhlig', id: 18},
  { value: 'Bahasa Indonesia', id: 19},
  { value: 'Norsk', id: 20},
  { value: 'русский', id: 21},
  { value: 'Slovenščina', id: 22},
]
